### ISSUE TITLE
Error on 'make' - error: too few arguments to function cudnnStatus_t cudnnSetFilter4dDescriptor

### ISSUE THREAD

**Issue by thedonquixotic** [andersbll/cudarray#56] opened 2016-05-25 23:50 UTC
Just tried to get this setup today, running into an issue while 'make'-ing cudarray.

Any suggestions?

```
g++ -DCUDNN_ENABLED -Wall -I./include -I/usr/local/cuda/include -c -o src/nnet/cudnn.o src/nnet/cudnn.cpp
In file included from /usr/local/cuda/include/cuda_runtime_api.h:133:0,
                 from ./include/cudarray/common.hpp:8,
                 from src/nnet/cudnn.cpp:4:
/usr/local/cuda/include/host_defines.h:84:0: warning: "__cdecl" redefined
 #define __cdecl
 ^

<built-in>: note: this is the location of the previous definition
In file included from src/nnet/cudnn.cpp:5:0:
src/nnet/cudnn.cpp: In member function ‘void cudarray::PoolBC01CuDNN<T>::fprop(const T*, int*, T*)’:
src/nnet/cudnn.cpp:76:5: error: too few arguments to function ‘cudnnStatus_t cudnnSetPoolingNdDescriptor(cudnnPoolingDescriptor_t, cudnnPoolingMode_t, cudnnNanPropagation_t, int, const int*, const int*, const int*)’
     ));
     ^

./include/cudarray/nnet/cudnn.hpp:87:44: note: in definition of macro ‘CUDNN_CHECK’
 #define CUDNN_CHECK(status) { cudnn_check((status), __FILE__, __LINE__); }
                                            ^
In file included from ./include/cudarray/nnet/cudnn.hpp:8:0,
                 from src/nnet/cudnn.cpp:5:
/usr/local/cuda/include/cudnn.h:821:27: note: declared here
 cudnnStatus_t CUDNNWINAPI cudnnSetPoolingNdDescriptor(
                           ^

In file included from src/nnet/cudnn.cpp:5:0:
src/nnet/cudnn.cpp: In member function ‘void cudarray::ConvBC01CuDNN<T>::fprop(const T*, const T*, int, int, int, int, int, int, int, T*)’:
src/nnet/cudnn.cpp:158:5: error: too few arguments to function ‘cudnnStatus_t cudnnSetFilter4dDescriptor(cudnnFilterDescriptor_t, cudnnDataType_t, cudnnTensorFormat_t, int, int, int, int)’
     ));
     ^

./include/cudarray/nnet/cudnn.hpp:87:44: note: in definition of macro ‘CUDNN_CHECK’
 #define CUDNN_CHECK(status) { cudnn_check((status), __FILE__, __LINE__); }
                                            ^

In file included from ./include/cudarray/nnet/cudnn.hpp:8:0,
                 from src/nnet/cudnn.cpp:5:
/usr/local/cuda/include/cudnn.h:320:27: note: declared here
 cudnnStatus_t CUDNNWINAPI cudnnSetFilter4dDescriptor(
                           ^

Makefile:73: recipe for target 'src/nnet/cudnn.o' failed
make: *** [src/nnet/cudnn.o] Error 1

```

**Comment by andersbll** [comment] 2016-05-26 07:19
The problem is a mismatching version of cuDNN. I think you have installed cuDNN v5 RC. If so, you should checkout the cudnn5 branch of CUDArray. When v5 is no longer a release candidate, the cudnn5 branch will be merged to master. Currently, the master branch requires cuDNN v4.

**Comment by andersbll** [comment] 2016-05-26 17:43
cuDNN v5 was just released today. I have merged the cudnn5 branch into master. :)

**Comment by thedonquixotic** [comment] 2016-05-26 17:59
Sweet! I was just going to ask you about that after seeing the email update from them :)

And just to make sure I do the right thing (non-code artist/designer speaking here), I need to redownload/install the cudnn master, the cudarray master, or the neural style master?

**Comment by andersbll** [comment] 2016-05-26 18:04
A `git pull` should suffice for CUDArray. Just overwrite your cuDNN 5 RC installation with the latest cuDNN from Nvidia.

**Comment by thedonquixotic** [comment] 2016-05-27 03:11
Sorry to annoy. I tried reinstalling all the dependcies in a more organized fashion, updating them with the latest versions on github etc, to help with the cuDNN 5 issue etc. and I still seem to be running into an error. I think it's some kind of pathing error?

`$ make
g++ -DCUDNN_ENABLED -O3 -fPIC -Wall -Wfatal-errors -I./include -IC:\Program -IFi                                                                                                      les\NVIDIA -IGPU -IComputing -IToolkit\CUDA\v7.5/include -c -o src/nnet/conv_bc0                                                                                                      1_matmul.o src/nnet/conv_bc01_matmul.cpp
src/nnet/conv_bc01_matmul.cpp:1:0: warning: -fPIC ignored for target (all code i                                                                                                      s position independent)
 #include "cudarray/common.hpp"
 ^
In file included from src/nnet/conv_bc01_matmul.cpp:1:0:
./include/cudarray/common.hpp:8:30: fatal error: cuda_runtime_api.h: No such fil                                                                                                      e or directory
 #include <cuda_runtime_api.h>
                              ^
compilation terminated.
Makefile:75: recipe for target 'src/nnet/conv_bc01_matmul.o' failed
make: *** [src/nnet/conv_bc01_matmul.o] Error 1
`

Very sorry for my ignorance here! Like I said, I am by no means a coder so I'm learning a lot haha

**Comment by thedonquixotic** [comment] 2016-05-27 03:12
I should also say that I'm trying to install this on a windows machine using cygwin, if that's at all relevant.

**Comment by thedonquixotic** [comment] 2016-05-30 19:15
Okay so I figured out some of what's going on. It's definetly because I'm using Windows. Basically I'm going through the make file and trying to slowly change it so that it will run according to my Windows directory. I'm figuring it out slowly. If I get this all done, would you like me to package it up for Windows people to use?

**Comment by N2ITN** [comment] 2016-05-31 17:12
Do you think the issue with Windows the fact that there are spaces in the CUDA toolkit path?  I've been trying to compile on windows, and get the same "#include <cuda_runtime_api.h>" error, leading me to believe its the CUDA path, since that file is where it should be on my mchine, and I can use CUDA with Keras/Theano.

If you do get a Windows binary going, I would certainly use it.

**Comment by andersbll** [comment] 2016-06-02 07:02
Hey, installing CUDArray on Windows can be really painful. Unfortunately, I can't help you with that part. :/

**Comment by thedonquixotic** [comment] 2016-06-19 01:55
Yeah, I gave up actually. I just made a bootable ubuntu drive for me to do neural network stuff on. I think I've got it working though! Thank you for your help :)

**Closed** 2016-06-19 01:55 UTC

**Comment by oxydron** [comment] 2016-11-13 19:44
Tried to install it on elementaryOS Loki 0.4 (Ubuntu) and got the same message.

```
g++ -DCUDNN_ENABLED -O3 -fPIC -Wall -Wfatal-errors -D_FORCE_INLINES -I./include -I/usr/local/cuda/include -c -o src/nnet/conv_bc01_matmul.o src/nnet/conv_bc01_matmul.cpp
In file included from src/nnet/conv_bc01_matmul.cpp:1:0:
./include/cudarray/common.hpp:8:30: fatal error: cuda_runtime_api.h: No such file or directory
compilation terminated.
Makefile:75: recipe for target 'src/nnet/conv_bc01_matmul.o' failed
make: *** [src/nnet/conv_bc01_matmul.o] Error 1

```
